apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: my-movie-app
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: my-movie-container
